# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14dd4e57c4b54e8d7e7088b40c8c6061e3b305ed4685b2de6f294600185f266e55599380d11eb194fd6e50d2ffef4f9a3ff7b11a9c79877ea125112d8a7497b7

test:
  secret_key_base: 18491d2d3371666be6441bd614f28775041a0eacabacf012943494f2527570c61721e935c7b655e59c851bd39c3f095fb6de720676aa6b35cb3d3069db2003c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
